command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8080"

resources:
  cpu: 2
  memory: 4Gi

env:
  - name: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: "false"